Repository harshgoel05/another-portfolio, pull requests merged in 2021-10, with the labels that each got.

#92 Add Hacktoberfest Docs
  .env.example
  CONTRIBUTING.md
  README.md
Labels: documentation

#95 💄 Fix word breaks in github section
  api/utils/db.ts
  components/home/repo.tsx
  styles/global.css
Labels: hacktoberfest-accepted

#96 💄 Active state indicator for Explore
  shared/components/navbar.tsx
Labels: bug, good first issue
